### ISSUE TITLE
Neue Kurstypen / Alias-Funktion

### ISSUE THREAD

**Issue by domwass** [jspitz/jslectureplanner#1]
Lieber Jürgen,

erst einmal vielen Dank für das sehr schöne Paket. Ich will es im nächsten Semester einsetzen und habe jetzt einmal ein bisschen damit herumgespielt. Für die Kurse an unserem Institut (Historisches Institut an der Universität zu Köln) bräuchte ich mehr Kurstypen, denn neben Proseminaren (die bei uns Einführungsseminare heißen) haben wir Aufbauseminare (AS) und Hauptseminare (HS). Ein einfaches Umbenennen des Typs Seminar (SE) reicht hier also nicht aus. Außerdem gibt es neben klassischen Vorlesungen auch sogenannte Einführungsvorlesungen (EVL). 

Außerdem wäre es schön, wenn es eine Art Alias-Funktion gäbe, denn dann müsste ich mir nicht merken, dass ich z.B. Übungen (UE) in Arbeitskurse (AK) umbenannt habe und bei einem AK dann type=UE auswählen muss. Ich stelle mir das so vor, dass man beispielsweise eingibt 

``` latex
\typealias{ak}{ue}
```

und dann einfach mit `type=ak` anwählen kann.

Vielen Dank nochmal,
Dominik.-

**Comment by jspitz** [comment]
Dominik
I took the opportunity to remove the hardcoding of lecture types. You can now freely add new types via the new macro \DefLecType. This renders the \typealias proposal obsolete IMHO.

As to the proposed additions, I would rather introduce styles for different conventions rather than extending the default list ad infinitum.

I have added a draft for a "cologne" style (cologne.lps file), which implements the types you need. You can load it via the "style=cologne" package option and then use the new lecture types evl, as, es, hs and ak.

Could you please test this and tweak the style, if needed? I'llinclude it to the package then.

**Comment by domwass** [comment]
Jürgen
Works perfectly, thanks a lot. Using this solution, the \typealias proposal is, indeed, not necessary.

**Comment by jspitz** [comment]
OK, great. What about the "cologne" style file? Should I ship it as is, or do you want to make some modifications?

**Comment by domwass** [comment]
Would it be possible to load more than one style file? I’d like to tweak the date output, but that is nothing specific to “cologne”, but on the other hand it would be tedious to copy it into every metadata file.

**Comment by jspitz** [comment]
You can load one style file only. However, you can set up your own style file dominik.lps (in your local texmf tree) which loads cologne via \input{cologne.lps} and then tweaks the date output.

Does that fit your needs?

**Comment by domwass** [comment]
Yes, this would fit. In that case, you can ship the “cologne” file as is.

**Comment by jspitz** [comment]
V. 1.0 is approaching CTAN.
